from typing import Protocol, list as _l
class AIProvider(Protocol):
    name: str
    def chat(self, messages: list, model: str = "") -> dict: ...
    def structured_output(self, messages: list, schema: dict, model: str = "") -> dict: ...
    def health_check(self) -> dict: ...
    def estimate_cost(self, inp: int, out: int) -> float: ...
