"""Emit app/static/js/viewdocs.js from app/docs_data.py (single source of truth).

Run from repo root:  python scripts/docs/gen_viewmap.py
Regenerate whenever VIEW_DOCS changes. Validated by tests (every value must
be a real docs slug, every key a real frontend view).
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "source", "python"))
os.environ.setdefault("DATABASE_URL", "sqlite:///:memory:")

from app import docs_data as D  # noqa: E402

SECTION_HELP = {
    "Investigate": ("Start and follow investigations: targets, entities, graph and timeline.",
                    "Open New Investigation, or triage from Investigations and Cases.",
                    "Starting work without checking which project is selected."),
    "Discover": ("Register what to watch and run collection: targets, scans, collectors and feeds.",
                 "Add a target, test the connection, then scan on demand or on schedule.",
                 "Scanning systems you are not authorized to investigate."),
    "Intelligence": ("Turn collections into understanding: findings, indicators, risk and feed.",
                     "Triage findings first; every score links to its evidence.",
                     "Quoting a risk score as proof of malicious activity."),
    "Monitor": ("Keep watching after you leave: watchlists, alerts and workflows.",
                "Watch a keyword or domain, then attach an alert rule.",
                "Watching overly broad keywords creates alert noise."),
    "Evidence": ("Preserve and present: evidence, documents, cases and reports.",
                 "Cite evidence records — UI screenshots are illustrations, not evidence.",
                 "Editing a report to say what the evidence does not."),
    "Integrations": ("Exchange with the outside world: STIX/MISP, API keys, tools and AI.",
                     "Export the documented subset; validate before trusting imports.",
                     "Assuming full STIX compatibility beyond the documented subset."),
    "Administration": ("Run the platform: members, settings, audit and health.",
                       "Check System Health first when anything behaves oddly.",
                       "Changing security settings without noting the previous value."),
}

VIEW_SECTION_FALLBACK = {}
for _view, _slug in D.VIEW_DOCS.items():
    _page = D.page_by_slug(_slug)
    if _page:
        _sec = D.section_by_id(_page[1])
        if _sec:
            VIEW_SECTION_FALLBACK[_view] = _sec["name"]["en"]

# map section EN name -> help blurb
HELP = {sec: {"what": w, "how": h, "mistake": m} for sec, (w, h, m) in SECTION_HELP.items()}

payload = {"docs": D.VIEW_DOCS, "sections": VIEW_SECTION_FALLBACK, "help": HELP}
js = ("/* Generated by scripts/docs/gen_viewmap.py — do not edit by hand. */\n"
      "window.VIEW_DOCS=" + json.dumps(payload["docs"]) + ";\n"
      "window.VIEW_SECTION=" + json.dumps(payload["sections"]) + ";\n"
      "window.VIEW_HELP=" + json.dumps(payload["help"]) + ";\n")

out = os.path.join(ROOT, "source", "python", "app", "static", "js", "viewdocs.js")
with open(out, "w", encoding="utf-8") as fh:
    fh.write(js)
print("wrote", out, len(D.VIEW_DOCS), "views")
