"""Docs portal registry: single source of truth for navigation, search, sitemap,
prev/next, contextual help and screenshot planning.

Every `api` prefix MUST match real paths in contracts/openapi/openapi.json
(validated by tests). Every `app` value MUST be a real frontend hash route
(validated by tests against app/static/js/views.js NAV + VIEW_TITLE).
"""
from __future__ import annotations

VERSION_FALLBACK = "2.0.0"

SECTION_LIST = [
    ("getting-started", 10, "home", "Getting Started", "Memulai", "البدء"),
    ("investigations", 20, "search", "Investigations", "Investigasi", "التحقيقات"),
    ("discovery", 30, "radar", "Discovery", "Penemuan", "الاكتشاف"),
    ("intelligence", 40, "graph", "Intelligence", "Intelijen", "الاستخبارات"),
    ("evidence", 50, "file", "Evidence", "Bukti", "الأدلة"),
    ("monitoring", 60, "bell", "Monitoring", "Pemantauan", "المراقبة"),
    ("integrations", 70, "plug", "Integrations", "Integrasi", "التكاملات"),
    ("ai", 80, "spark", "AI", "AI", "الذكاء الاصطناعي"),
    ("administration", 90, "gear", "Administration", "Administrasi", "الإدارة"),
    ("security", 100, "shield", "Security", "Keamanan", "الأمان"),
    ("deployment", 110, "server", "Deployment", "Penerapan", "النشر"),
    ("api", 120, "code", "API", "API", "API"),
    ("troubleshooting", 130, "wrench", "Troubleshooting", "Pemecahan Masalah", "استكشاف الأخطاء"),
    ("reference", 140, "book", "Reference", "Referensi", "المرجع"),
    ("changelog", 150, "tag", "Changelog", "Catatan Rilis", "سجل التغييرات"),
]

# code -> {order, icon, name:{en,id,ar}}
SECTIONS = [
    {"code": c, "order": o, "icon": i,
     "name": {"en": en, "id": id_, "ar": ar}}
    for (c, o, i, en, id_, ar) in SECTION_LIST
]

# (slug, section, kind, order, app-route, api-prefixes, shots, kw,
#  title_en, title_id, title_ar, desc_en)
# kind: home|tutorial|tutorial-short|lifecycle|howto|concept|api|reference|troubleshooting|deployment|glossary
PAGES = [
    # ---------------- getting started ----------------
    ("index", "getting-started", "home", 1, "dashboard", ["/api/v1/dashboard"],
     ["02-dashboard.png"],
     ["overview", "introduction", "start", "mulai", "platform"],
     "Web Intelligence Documentation",
     "Dokumentasi Web Intelligence",
     "توثيق Web Intelligence",
     "Search, investigate, connect, correlate, assess risk, preserve evidence, build cases, report and monitor."),
    ("getting-started/overview", "getting-started", "concept", 5, "dashboard", ["/api/v1/dashboard", "/api/version"],
     ["02-dashboard.png"],
     ["overview", "platform", "workflow", "concepts"],
     "What Is Web Intelligence?",
     "Apa Itu Web Intelligence?",
     "ما هي Web Intelligence؟",
     "The Intelligence & Investigation Platform: from search to monitoring in one workspace."),
    ("getting-started/login", "getting-started", "howto", 10, "login", ["/api/v1/auth/login"],
     ["01-login.png"],
     ["login", "sign in", "auth", "masuk", "token"],
     "Sign In & Authentication",
     "Masuk & Autentikasi",
     "تسجيل الدخول والمصادقة",
     "Sign in with a Bearer token or API key, or run open in local development."),
    ("getting-started/dashboard", "getting-started", "howto", 15, "dashboard", ["/api/v1/dashboard"],
     ["02-dashboard.png"],
     ["dashboard", "kpi", "dasbor", "overview"],
     "Using the Dashboard",
     "Menggunakan Dasbor",
     "استخدام لوحة التحكم",
     "Read the hero dashboard: KPIs, trends, risk, graph preview and activity — all real data."),
    ("getting-started/first-investigation", "getting-started", "tutorial", 20, "new-investigation",
     ["/api/v1/investigations", "/api/v1/targets", "/api/v1/jobs", "/api/v1/risk/target"],
     ["03-new-investigation.png", "04-target-type.png", "05-target.png", "06-scope.png",
      "08-review.png", "09-queued.png", "10-running.png", "11-completed.png",
      "12-findings.png", "14-graph.png", "15-risk.png", "17-evidence.png",
      "18-case.png", "19-report.png", "20-watchlist.png", "21-alert.png", "22-workflow.png"],
     ["first", "tutorial", "investigation", "domain", "pertama", "walkthrough"],
     "Your First Investigation",
     "Investigasi Pertama Anda",
     "أول تحقيق لك",
     "A complete 20-step walkthrough: domain to report, with real screenshots at every step."),
    ("getting-started/5-minute-investigation", "getting-started", "tutorial-short", 25, "new-investigation",
     ["/api/v1/investigations", "/api/v1/dashboard"],
     ["03-new-investigation.png", "11-completed.png", "14-graph.png", "15-risk.png", "19-report.png"],
     ["quickstart", "5 minute", "cepat", "results"],
     "5 Minutes to First Result",
     "5 Menit ke Hasil Pertama",
     "خمس دقائق إلى أول نتيجة",
     "Understand the entire product in five minutes: login to report in ten steps."),
    # ---------------- investigations ----------------
    ("investigations/create-investigation", "investigations", "howto", 10, "new-investigation",
     ["/api/v1/investigations"],
     ["03-new-investigation.png", "08-review.png"],
     ["create", "new", "wizard", "buat"],
     "Create an Investigation",
     "Membuat Investigasi",
     "إنشاء تحقيق",
     "Use the 5-step wizard: type, target, depth, scope, review — then start."),
    ("investigations/target-types", "investigations", "concept", 20, "new-investigation",
     ["/api/v1/investigations", "/api/v1/search"],
     ["04-target-type.png"],
     ["domain", "ip", "email", "organization", "keyword", "target types"],
     "Target Types",
     "Jenis Target",
     "أنواع الأهداف",
     "Domain, URL, IP, email, organization, identity or keyword — what each unlocks."),
    ("investigations/scope", "investigations", "howto", 30, "new-investigation",
     ["/api/v1/investigations"],
     ["06-scope.png"],
     ["scope", "dns", "tls", "subdomains", "cakupan"],
     "Choosing Scope",
     "Memilih Cakupan",
     "اختيار النطاق",
     "DNS, subdomains, TLS, technologies, content, infrastructure, documents, threat intel and risk."),
    ("investigations/sources", "investigations", "howto", 40, "data-sources",
     ["/api/v1/projects", "/api/v1/targets", "/api/v1/connectors"],
     ["07-sources.png"],
     ["sources", "projects", "targets", "sumber"],
     "Projects, Targets & Sources",
     "Proyek, Target & Sumber",
     "المشاريع والأهداف والمصادر",
     "Organize work in projects; register targets; test connections before collecting."),
    ("investigations/profiles", "investigations", "concept", 50, "new-investigation",
     ["/api/v1/investigations"],
     [],
     ["profile", "quick", "standard", "deep", "depth", "profil"],
     "Investigation Profiles: Quick, Standard, Deep",
     "Profil Investigasi: Cepat, Standar, Mendalam",
     "ملفات التحقيق: سريع، قياسي، عميق",
     "What each depth collects, how long it takes, and when to use it."),
    ("investigations/collection", "investigations", "howto", 60, "jobs",
     ["/api/v1/jobs", "/api/v1/results", "/api/v1/dlq", "/api/v1/worker/tick"],
     ["09-queued.png", "10-running.png", "11-completed.png"],
     ["collection", "queued", "running", "success", "failed", "cancelled", "jobs"],
     "Collection: Queued, Running, Success",
     "Koleksi: Antre, Berjalan, Sukses",
     "الجمع: في الانتظار، قيد التشغيل، ناجح",
     "Every async operation exposes queued, running, success, failed and cancelled — with retry and cancel."),
    ("investigations/investigation-lifecycle", "investigations", "lifecycle", 70, "investigations",
     ["/api/v1/investigations", "/api/v1/cases"],
     ["11-completed.png"],
     ["lifecycle", "workflow", "stages", "siklus"],
     "The Investigation Lifecycle",
     "Siklus Hidup Investigasi",
     "دورة حياة التحقيق",
     "Search to monitor: every stage of the pipeline, clickable into its guide."),
    ("search", "investigations", "howto", 75, "search",
     ["/api/v1/search", "/api/v1/search/semantic"],
     ["31-search.png", "32-search-results.png"],
     ["search", "keyword", "semantic", "hybrid", "exact", "ranking", "pencarian"],
     "Search Console",
     "Konsol Pencarian",
     "وحدة البحث",
     "One engine, four modes: keyword, exact, semantic and hybrid — with ranking, filters and honest empty states."),
    # ---------------- discovery ----------------
    ("discovery/targets", "discovery", "howto", 10, "targets",
     ["/api/v1/targets", "/api/v1/reliability/targets"],
     [],
     ["targets", "reliability", "target"],
     "Targets",
     "Target",
     "الأهداف",
     "Register, test, scan, schedule and evaluate targets; read reliability scores."),
    ("discovery/reconnaissance", "discovery", "howto", 20, "recon",
     ["/api/v1/jobs", "/api/v1/attack-surface"],
     [],
     ["recon", "reconnaissance", "dns", "tls", "scanning"],
     "Reconnaissance",
     "Reconnaissance",
     "الاستطلاع",
     "DNS, TLS, technologies, robots and deep RDAP/WHOIS scans — and infra-correlation findings."),
    ("discovery/attack-surface", "discovery", "howto", 30, "attack",
     ["/api/v1/attack-surface"],
     [],
     ["attack surface", "assets", "exposure", "permukaan serangan"],
     "Attack Surface",
     "Permukaan Serangan",
     "سطح الهجوم",
     "See every exposed asset for a target in one overview."),
    ("discovery/collectors", "discovery", "howto", 40, "collectors",
     ["/api/v1/collectors", "/api/v1/strategy/decide", "/api/v1/proxies/health",
      "/api/v1/brightdata/test", "/api/v1/browser/health"],
     [],
     ["collectors", "go collector", "strategy", "proxy", "kolektor"],
     "Collectors",
     "Kolektor",
     "الجامعون",
     "The Go collector engine, the strategy ladder DIRECT to BRIGHT_DATA, proxies and the browser pool."),
    ("discovery/connectors", "discovery", "howto", 50, "connectors",
     ["/api/v1/connectors"],
     [],
     ["connectors", "rss", "rest", "csv", "konektor"],
     "Connectors",
     "Konektor",
     "الموصلات",
     "RSS, paginated REST and CSV connectors: match, test and execute into articles and datasets."),
    ("discovery/data-sources", "discovery", "howto", 60, "data-sources",
     ["/api/v1/projects", "/api/v1/targets", "/api/v1/connectors", "/api/v1/documents"],
     ["07-sources.png"],
     ["data sources", "projects", "documents", "sumber data"],
     "Data Sources",
     "Sumber Data",
     "مصادر البيانات",
     "Projects, targets, connectors and documents as the four source families."),
    # ---------------- intelligence ----------------
    ("intelligence/entities", "intelligence", "howto", 10, "entities",
     ["/api/v1/entities"],
     ["13-entities.png"],
     ["entities", "entitas", "people", "companies", "domains"],
     "Entities",
     "Entitas",
     "الكيانات",
     "Browse people, companies, domains, IPs, emails and technologies with confidence scores."),
    ("intelligence/entity-resolution", "intelligence", "howto", 20, "entities",
     ["/api/v1/entities/resolve", "/api/v1/entities/merge", "/api/v1/entities/split",
      "/api/v1/entities/reject"],
     [],
     ["entity resolution", "merge", "split", "dedup", "resolusi"],
     "Entity Resolution",
     "Resolusi Entitas",
     "حل الكيانات",
     "Resolve, merge, split and reject: turn noisy mentions into confident identities."),
    ("intelligence/graph", "intelligence", "howto", 30, "graph",
     ["/api/v1/graph/nodes", "/api/v1/graph/traverse"],
     ["14-graph.png"],
     ["graph", "nodes", "edges", "traverse", "graf"],
     "Intelligence Graph",
     "Graf Intelijen",
     "الرسم البياني الاستخباري",
     "Nodes, edges, traversal, shortest path and SVG rendering — investigate a domain through the graph."),
    ("intelligence/pivoting", "intelligence", "howto", 40, "graph",
     ["/api/v1/transforms/run", "/api/v1/graph/path"],
     [],
     ["pivot", "transforms", "path", "traversal"],
     "Pivoting & Transforms",
     "Pivoting & Transformasi",
     "الانتقال والتحويلات",
     "Domain to IP to domain, certificate, technology and email pivots that expand an investigation."),
    ("intelligence/findings", "intelligence", "howto", 50, "findings",
     ["/api/v1/findings"],
     ["12-findings.png"],
     ["findings", "triage", "temuan"],
     "Findings",
     "Temuan",
     "النتائج",
     "Triage correlated findings with severity, confidence, evidence and lineage."),
    ("intelligence/indicators", "intelligence", "howto", 60, "indicators",
     ["/api/v1/findings"],
     [],
     ["indicators", "ioc", "indikator"],
     "Indicators",
     "Indikator",
     "المؤشرات",
     "Indicators of compromise distilled from findings, ready for STIX/MISP export."),
    ("intelligence/risk", "intelligence", "howto", 70, "risk",
     ["/api/v1/risk/target", "/api/v1/risk/entity"],
     ["15-risk.png"],
     ["risk", "score", "0-100", "risiko", "factors"],
     "Risk Analysis",
     "Analisis Risiko",
     "تحليل المخاطر",
     "Explainable 0-100 risk: factors plus evidence. A signal for analysts — never proof of malice."),
    ("intelligence/timeline", "intelligence", "howto", 80, "timeline",
     ["/api/v1/timeline"],
     ["16-timeline.png"],
     ["timeline", "events", "linimasa", "chronology"],
     "Timeline",
     "Linimasa",
     "الخط الزمني",
     "Every event in chronological order with filters — the story of an investigation."),
    ("intelligence/threat-intelligence", "intelligence", "howto", 90, "threat",
     ["/api/v1/feed", "/api/v1/stix/export"],
     [],
     ["threat intelligence", "feed", "ancaman"],
     "Threat Intelligence",
     "Intelijen Ancaman",
     "استخبارات التهديدات",
     "Consume the intelligence feed: subscriptions, personalized views and threat context."),
    ("intelligence/feed", "intelligence", "howto", 100, "intel-feed",
     ["/api/v1/feed", "/api/v1/feed/personalized", "/api/v1/feed/subscriptions"],
     [],
     ["feed", "subscriptions", "umpan"],
     "Intelligence Feed",
     "Umpan Intelijen",
     "الموجز الاستخباري",
     "Follow findings, changes and alerts as a live feed; subscribe and personalize."),
    # ---------------- evidence ----------------
    ("evidence/evidence", "evidence", "howto", 10, "evidence",
     ["/api/v1/evidence"],
     ["17-evidence.png"],
     ["evidence", "provenance", "bukti", "integrity"],
     "Evidence",
     "Bukti",
     "الأدلة",
     "Every claim points at evidence: source, timestamp, integrity and provenance."),
    ("evidence/documents", "evidence", "howto", 20, "documents",
     ["/api/v1/documents"],
     [],
     ["documents", "ingest", "pdf", "dokumen"],
     "Documents",
     "Dokumen",
     "المستندات",
     "Ingest txt, html, csv and pdf into the evidence store."),
    ("evidence/claims", "evidence", "howto", 30, "evidence",
     ["/api/v1/claims", "/api/v1/claims/verify", "/api/v1/contradictions/check"],
     [],
     ["claims", "verification", "contradiction", "klaim"],
     "Claims & Verification",
     "Klaim & Verifikasi",
     "الادعاءات والتحقق",
     "Evidence-grounded claims, verification against sources, and contradiction detection."),
    ("evidence/lineage", "evidence", "concept", 40, "findings",
     ["/api/v1/lineage"],
     [],
     ["lineage", "provenance", "silsilah", "data lineage"],
     "Data Lineage",
     "Silsilah Data",
     "نسب البيانات",
     "Trace any finding back to the raw collection that produced it."),
    ("evidence/cases", "evidence", "howto", 50, "cases",
     ["/api/v1/cases"],
     ["18-case.png"],
     ["cases", "notes", "tasks", "members", "kasus"],
     "Cases",
     "Kasus",
     "القضايا",
     "From investigation to case: notes, tasks, members, links, evidence and reports."),
    ("evidence/reports", "evidence", "howto", 60, "reports",
     ["/api/v1/reports"],
     ["19-report.png"],
     ["reports", "export", "pdf", "csv", "laporan"],
     "Reports",
     "Laporan",
     "التقارير",
     "Generate and export reports: web, PDF, CSV, JSON, XLSX and Markdown."),
    # ---------------- monitoring ----------------
    ("monitoring/watchlists", "monitoring", "howto", 10, "watchlists",
     ["/api/v1/watchlists"],
     ["20-watchlist.png"],
     ["watchlists", "keyword", "domain", "daftar pantau"],
     "Watchlists",
     "Daftar Pantau",
     "قوائم المراقبة",
     "Watch keywords, companies and domains; evaluate on demand."),
    ("monitoring/alerts", "monitoring", "howto", 20, "alerts",
     ["/api/v1/alerts"],
     ["21-alert.png"],
     ["alerts", "ack", "resolve", "incidents", "peringatan"],
     "Alerts",
     "Peringatan",
     "التنبيهات",
     "Acknowledge, resolve, bulk-triage and escalate alerts into incidents."),
    ("monitoring/workflows", "monitoring", "howto", 30, "workflows",
     ["/api/v1/workflows"],
     ["22-workflow.png"],
     ["workflows", "trigger", "action", "retry", "cancel", "alur kerja"],
     "Workflows",
     "Alur Kerja",
     "سير العمل",
     "Trigger-to-action automation with runs, idempotent retry and cancel."),
    ("monitoring/webhooks", "monitoring", "howto", 40, "webhooks",
     ["/api/v1/webhooks"],
     [],
     ["webhooks", "deliveries", "replay", "outbound"],
     "Outbound Webhooks",
     "Webhook Keluar",
     "الويب هوك الصادر",
     "Deliver events to your systems; inspect deliveries and replay failures."),
    # ---------------- integrations ----------------
    ("integrations/stix", "integrations", "howto", 10, "stix",
     ["/api/v1/stix/export", "/api/v1/stix/validate", "/api/v1/stix/import"],
     ["24-stix.png"],
     ["stix", "2.1", "bundle", "export", "import"],
     "STIX 2.1",
     "STIX 2.1",
     "STIX 2.1",
     "Export bundles, validate, and import with dedupe and evidence provenance."),
    ("integrations/misp", "integrations", "howto", 20, "stix",
     ["/api/v1/misp/export", "/api/v1/misp/import"],
     ["25-misp.png"],
     ["misp", "event", "attribute", "galaxy"],
     "MISP",
     "MISP",
     "MISP",
     "Exchange events and attributes with MISP; know exactly which subset is supported."),
    ("integrations/security-tools", "integrations", "howto", 30, "security-tools",
     ["/healthz", "/readyz"],
     ["33-security-tools.png"],
     ["security tools", "adapters", "health check", "perkakas"],
     "Security Tools",
     "Perkakas Keamanan",
     "أدوات الأمان",
     "Connect the tools you already run: configuration, health checks and expected output."),
    ("integrations/external-apis", "integrations", "howto", 40, "external-apis",
     ["/api/v1/apikeys", "/api/v1/ingest/webhook"],
     ["34-external-apis.png", "28-api.png"],
     ["api keys", "external", "ingest", "eksternal"],
     "External APIs",
     "API Eksternal",
     "واجهات خارجية",
     "Scoped API keys for outside clients and HMAC-signed inbound ingestion."),
    ("integrations/ai", "integrations", "concept", 50, "ai-providers",
     ["/api/v1/ai/providers"],
     ["23-ai-provider.png"],
     ["ai", "providers", "overview", "kecerdasan"],
     "AI Overview",
     "Gambaran AI",
     "نظرة على الذكاء الاصطناعي",
     "How AI plugs into investigations — start here, then read the AI section."),
    # ---------------- ai ----------------
    ("ai/providers", "ai", "howto", 10, "ai-providers",
     ["/api/v1/ai/providers", "/api/v1/ai/models", "/api/v1/ai/health", "/api/v1/ai/default"],
     ["23-ai-provider.png"],
     ["ai providers", "models", "health", "penyedia"],
     "AI Providers",
     "Penyedia AI",
     "مزودو الذكاء الاصطناعي",
     "Add a provider, test the live connection, discover models, then save."),
    ("ai/provider-configuration", "ai", "howto", 20, "ai-providers",
     ["/api/v1/ai/providers/db"],
     [],
     ["configuration", "credentials", "openai", "anthropic", "ollama", "konfigurasi"],
     "Provider Configuration",
     "Konfigurasi Penyedia",
     "تكوين المزود",
     "OpenAI-compatible, Anthropic-compatible, Google-compatible and Ollama-style endpoints."),
    ("ai/evidence-grounded-ai", "ai", "concept", 30, "ai-providers",
     ["/api/v1/ai/chat", "/api/v1/ask"],
     [],
     ["evidence grounded", "citations", "chat", "ask", "berbasis bukti"],
     "Evidence-Grounded AI",
     "AI Berbasis Bukti",
     "ذكاء اصطناعي موثق بالأدلة",
     "Answers cite evidence_ids. AI output is labeled AI-generated — never evidence itself."),
    ("ai/research", "ai", "howto", 40, "research",
     ["/api/v1/research/plan", "/api/v1/research/runs"],
     [],
     ["research", "runs", "plan", "analyze", "riset"],
     "Research Runs",
     "Jalannya Riset",
     "جولات البحث",
     "Plan, run, analyze, finish, compare and export research as Markdown."),
    ("ai/prompts", "ai", "reference", 50, "ai-providers",
     ["/api/v1/ai/prompts"],
     [],
     ["prompts", "registry", "prompt"],
     "Prompt Registry",
     "Registry Prompt",
     "سجل الموجهات",
     "Versioned prompts the platform uses — review what the AI is instructed to do."),
    ("ai/privacy", "ai", "concept", 60, "ai-providers",
     ["/api/v1/ai/usage"],
     [],
     ["privacy", "cost", "usage", "privasi", "data"],
     "AI Privacy & Cost",
     "Privasi & Biaya AI",
     "خصوصية الذكاء الاصطناعي والتكلفة",
     "What leaves your server, what stays, and how usage and cost are tracked."),
    # ---------------- administration ----------------
    ("administration/users", "administration", "howto", 10, "users",
     ["/api/v1/memberships"],
     [],
     ["users", "members", "disable", "pengguna"],
     "Users & Roles",
     "Pengguna & Peran",
     "المستخدمون والأدوار",
     "Invite members, change roles, disable logins — never lock out the last owner."),
    ("administration/roles", "administration", "reference", 20, "users",
     ["/api/v1/roles"],
     [],
     ["roles", "rbac", "permissions", "peran"],
     "Roles & Permissions",
     "Peran & Izin",
     "الأدوار والأذونات",
     "Built-in and custom roles: exactly what each permission unlocks."),
    ("administration/organizations", "administration", "howto", 30, "users",
     ["/api/v1/orgs"],
     [],
     ["organizations", "branding", "white label", "organisasi"],
     "Organizations & Branding",
     "Organisasi & Branding",
     "المنظمات والهوية",
     "Isolate data per organization and apply white-label branding."),
    ("administration/api-keys", "administration", "howto", 40, "external-apis",
     ["/api/v1/apikeys"],
     [],
     ["api keys", "scoped", "expiring", "revoke", "kunci"],
     "API Keys",
     "Kunci API",
     "مفاتيح API",
     "Scoped, expiring keys shown once — revoke anytime."),
    ("administration/settings", "administration", "howto", 50, "settings",
     ["/api/v1/admin/retention/run", "/api/v1/flags"],
     ["26-settings.png"],
     ["settings", "retention", "flags", "billing", "pengaturan"],
     "Settings",
     "Pengaturan",
     "الإعدادات",
     "General, security, collectors, scheduler, notifications, storage, flags and billing."),
    ("administration/audit-log", "administration", "howto", 60, "audit",
     ["/api/v1/audit"],
     [],
     ["audit", "trail", "compliance", "jejak"],
     "Audit Log",
     "Log Audit",
     "سجل التدقيق",
     "Search and filter every recorded action for compliance and forensics."),
    ("administration/system-health", "administration", "howto", 70, "health",
     ["/api/v1/system/doctor"],
     ["27-system-health.png"],
     ["health", "doctor", "metrics", "kesehatan"],
     "System Health",
     "Kesehatan Sistem",
     "صحة النظام",
     "Readiness, the system doctor, metrics and what each signal means."),
    ("administration/backup", "administration", "howto", 80, "settings",
     ["/api/v1/admin/backup"],
     [],
     ["backup", "restore", "retention", "cadangan"],
     "Backup & Restore",
     "Cadangan & Pulihkan",
     "النسخ الاحتياطي والاستعادة",
     "MySQL dumps, SQLite file copies, retention runs and restore verification."),
    # ---------------- security ----------------
    ("security/authentication", "security", "howto", 10, "login",
     ["/api/v1/auth/login", "/api/v1/auth/oidc/login"],
     ["01-login.png"],
     ["authentication", "bearer", "oidc", "login", "otentikasi"],
     "Authentication",
     "Autentikasi",
     "المصادقة",
     "Bearer login, OIDC, token expiry and when REQUIRE_AUTH=1 matters."),
    ("security/rbac", "security", "concept", 20, "users",
     ["/api/v1/roles", "/api/v1/memberships"],
     [],
     ["rbac", "roles", "isolation", "idor"],
     "RBAC & Organization Isolation",
     "RBAC & Isolasi Organisasi",
     "التحكم بالوصول وعزل المنظمات",
     "Every collection is org-scoped and IDOR-tested. No magic project_id=1 fallback."),
    ("security/ssrf", "security", "concept", 30, "targets",
     ["/api/v1/targets"],
     [],
     ["ssrf", "allowlist", "egress", "protection"],
     "SSRF Protection",
     "Proteksi SSRF",
     "الحماية من SSRF",
     "Guard plus trusted-egress allowlist: what admins must configure."),
    ("security/api-security", "security", "concept", 40, "external-apis",
     ["/api/v1/auth/login"],
     [],
     ["rate limiting", "429", "413", "body size", "keamanan api"],
     "API Security",
     "Keamanan API",
     "أمان API",
     "Per-identity rate limits, body-size guards, request IDs and error envelopes."),
    ("security/webhooks", "security", "howto", 50, "webhooks",
     ["/api/v1/ingest/webhook"],
     [],
     ["hmac", "replay", "webhook security", "signature"],
     "Webhook Security",
     "Keamanan Webhook",
     "أمان الويب هوك",
     "Verify HMAC signatures and enforce the replay window on inbound ingestion."),
    ("security/secrets", "security", "howto", 60, "settings",
     [],
     [],
     ["secrets", "redaction", "rotation", "rahasia"],
     "Secrets Management",
     "Manajemen Rahasia",
     "إدارة الأسرار",
     "Encrypted provider keys, masked connector secrets, redacted logs — and rotation."),
    # ---------------- deployment ----------------
    ("deployment/requirements", "deployment", "reference", 10, "health",
     [],
     [],
     ["requirements", "python", "mysql", "redis", "go", "kebutuhan"],
     "Requirements",
     "Kebutuhan",
     "المتطلبات",
     "Exact versions for Python, MySQL, Redis, Go and browsers."),
    ("deployment/windows", "deployment", "deployment", 20, "health",
     [],
     [],
     ["windows", "venv", "laragon", "development"],
     "Windows Development",
     "Pengembangan Windows",
     "التطوير على ويندوز",
     "Venv to running server on Windows, including Laragon MySQL."),
    ("deployment/linux", "deployment", "deployment", 30, "health",
     [],
     [],
     ["linux", "systemd", "production"],
     "Linux Production",
     "Produksi Linux",
     "الإنتاج على لينكس",
     "Service units for API, worker, browser and collector."),
    ("deployment/aapanel", "deployment", "deployment", 40, "health",
     [],
     [],
     ["aapanel", "aa panel", "website", "database", "panel"],
     "aaPanel Guide",
     "Panduan aaPanel",
     "دليل aaPanel",
     "Fourteen steps: website to verified dashboard behind HTTPS."),
    ("deployment/nginx", "deployment", "deployment", 50, "health",
     [],
     [],
     ["nginx", "reverse proxy", "https", "subdirectory"],
     "Nginx & Reverse Proxy",
     "Nginx & Reverse Proxy",
     "Nginx والوكيل العكسي",
     "HTTPS termination, subdirectory hosting and header hardening."),
    ("deployment/mysql", "deployment", "deployment", 60, "health",
     [],
     [],
     ["mysql", "database", "8.4", "persistence"],
     "MySQL",
     "MySQL",
     "MySQL",
     "Create the database, wire DATABASE_URL, and understand write-through fallback."),
    ("deployment/redis", "deployment", "deployment", 70, "health",
     [],
     [],
     ["redis", "queue", "rate limit", "cache"],
     "Redis",
     "Redis",
     "Redis",
     "Queues and rate limits with Redis — and graceful behavior without it."),
    ("deployment/playwright", "deployment", "deployment", 80, "health",
     ["/api/v1/browser/health"],
     [],
     ["playwright", "browser", "headless", "pool", "peramban"],
     "Playwright & Browser Pool",
     "Playwright & Pool Browser",
     "Playwright ومجموعة المتصفح",
     "Two-context headless pool, per-job timeouts, media blocking."),
    ("deployment/go-collector", "deployment", "deployment", 90, "collectors",
     [],
     [],
     ["go", "collector", "build", "concurrency", "kolektor"],
     "Go Collector",
     "Kolektor Go",
     "جامع Go",
     "Build, configure and run the concurrent collection engine."),
    ("deployment/production-checklist", "deployment", "reference", 100, "health",
     [],
     [],
     ["production", "checklist", "https", "secrets", "produksi"],
     "Production Checklist",
     "Daftar Periksa Produksi",
     "قائمة الإنتاج",
     "Twenty checks before you call it production — all verifiable."),
    # ---------------- api ----------------
    ("api/overview", "api", "api", 5, "external-apis",
     [],
     ["28-api.png"],
     ["api", "overview", "openapi", "rest"],
     "API Overview",
     "Gambaran API",
     "نظرة على API",
     "Every versioned path under /api/v1, generated from the live OpenAPI contract."),
    ("api/authentication", "api", "api", 10, "login",
     ["/api/v1/auth/login", "/api/v1/apikeys"],
     [],
     ["auth", "bearer", "api key", "otentikasi"],
     "API Authentication",
     "Autentikasi API",
     "مصادقة API",
     "Bearer tokens and scoped API keys with curl, Python and JavaScript examples."),
    ("api/projects", "api", "api", 20, "data-sources",
     ["/api/v1/projects"],
     [],
     ["projects", "proyek"],
     "Projects API",
     "API Proyek",
     "API المشاريع",
     "Create and manage investigation workspaces."),
    ("api/investigations", "api", "api", 30, "investigations",
     ["/api/v1/investigations"],
     [],
     ["investigations", "lifecycle", "notes", "tasks"],
     "Investigations API",
     "API Investigasi",
     "API التحقيقات",
     "Full lifecycle plus notes, tasks, members, links and saved views."),
    ("api/targets", "api", "api", 40, "targets",
     ["/api/v1/targets"],
     [],
     ["targets", "test connection", "target"],
     "Targets API",
     "API Target",
     "API الأهداف",
     "Register targets and test connections with strategy advice."),
    ("api/jobs", "api", "api", 50, "jobs",
     ["/api/v1/jobs", "/api/v1/results", "/api/v1/dlq"],
     [],
     ["jobs", "run", "cancel", "retry", "results"],
     "Jobs API",
     "API Job",
     "API المهام",
     "Create, run, cancel and retry collection jobs; ingest results."),
    ("api/entities", "api", "api", 60, "entities",
     ["/api/v1/entities"],
     [],
     ["entities", "resolve", "merge", "entitas"],
     "Entities API",
     "API Entitas",
     "API الكيانات",
     "List, resolve, merge, split, reject and track entity history."),
    ("api/graph", "api", "api", 70, "graph",
     ["/api/v1/graph/nodes", "/api/v1/graph/traverse"],
     [],
     ["graph", "traverse", "path", "render", "graf"],
     "Graph API",
     "API Graf",
     "API الرسم البياني",
     "Nodes, edges, traversal, shortest path and SVG rendering."),
    ("api/findings", "api", "api", 80, "findings",
     ["/api/v1/findings", "/api/v1/lineage"],
     [],
     ["findings", "lineage", "temuan"],
     "Findings API",
     "API Temuan",
     "API النتائج",
     "Correlated findings with evidence lineage."),
    ("api/risk", "api", "api", 90, "risk",
     ["/api/v1/risk/target", "/api/v1/risk/entity"],
     [],
     ["risk", "score", "risiko"],
     "Risk API",
     "API Risiko",
     "API المخاطر",
     "Explainable 0-100 scores with factors and evidence."),
    ("api/evidence", "api", "api", 100, "evidence",
     ["/api/v1/evidence", "/api/v1/claims", "/api/v1/documents"],
     [],
     ["evidence", "claims", "documents", "bukti"],
     "Evidence API",
     "API Bukti",
     "API الأدلة",
     "Evidence store, claims, verification and document ingestion."),
    ("api/cases", "api", "api", 110, "cases",
     ["/api/v1/cases"],
     [],
     ["cases", "kasus"],
     "Cases API",
     "API Kasus",
     "API القضايا",
     "Build cases from investigations with tasks and links."),
    ("api/reports", "api", "api", 120, "reports",
     ["/api/v1/reports"],
     [],
     ["reports", "export", "laporan"],
     "Reports API",
     "API Laporan",
     "API التقارير",
     "Generate and export in six formats."),
    ("api/watchlists", "api", "api", 130, "watchlists",
     ["/api/v1/watchlists"],
     [],
     ["watchlists", "evaluate", "pantau"],
     "Watchlists API",
     "API Daftar Pantau",
     "API قوائم المراقبة",
     "Keyword, company and domain watches with evaluation."),
    ("api/alerts", "api", "api", 140, "alerts",
     ["/api/v1/alerts"],
     [],
     ["alerts", "ack", "incidents", "peringatan"],
     "Alerts API",
     "API Peringatan",
     "API التنبيهات",
     "Alert lifecycle, bulk operations and incidents."),
    ("api/workflows", "api", "api", 150, "workflows",
     ["/api/v1/workflows"],
     [],
     ["workflows", "run", "retry", "cancel", "alur"],
     "Workflows API",
     "API Alur Kerja",
     "API سير العمل",
     "Trigger-to-action automation with runs and retry."),
    ("api/connectors", "api", "api", 160, "connectors",
     ["/api/v1/connectors"],
     [],
     ["connectors", "rss", "execute", "konektor"],
     "Connectors API",
     "API Konektor",
     "API الموصلات",
     "RSS, REST and CSV ingestion with test and execute."),
    ("api/ai", "api", "api", 170, "ai-providers",
     ["/api/v1/ai/chat", "/api/v1/ask", "/api/v1/ai/providers"],
     [],
     ["ai", "chat", "ask", "providers"],
     "AI API",
     "API AI",
     "API الذكاء الاصطناعي",
     "Evidence-grounded chat, ask, providers and usage."),
    ("api/stix", "api", "api", 180, "stix",
     ["/api/v1/stix/export", "/api/v1/stix/validate", "/api/v1/stix/import"],
     [],
     ["stix", "bundle"],
     "STIX API",
     "API STIX",
     "API STIX",
     "STIX 2.1 bundles: export, validate, import."),
    ("api/misp", "api", "api", 190, "stix",
     ["/api/v1/misp/export", "/api/v1/misp/import"],
     [],
     ["misp", "event"],
     "MISP API",
     "API MISP",
     "API MISP",
     "MISP events: export and import."),
    ("api/errors", "api", "reference", 200, "external-apis",
     [],
     [],
     ["errors", "codes", "401", "403", "404", "429", "413", "500", "galat"],
     "Errors",
     "Galat",
     "الأخطاء",
     "Every error envelope, code and what to do about it."),
    ("api/rate-limits", "api", "reference", 210, "external-apis",
     [],
     [],
     ["rate limits", "429", "quota", "batas"],
     "Rate Limits",
     "Batas Laju",
     "حدود المعدل",
     "Per-identity cost classes, limits and Retry-After handling."),
    # ---------------- troubleshooting ----------------
    ("troubleshooting/common-errors", "troubleshooting", "troubleshooting", 10, "health",
     [],
     [],
     ["errors", "401", "500", "troubleshoot", "galat umum"],
     "Common Errors",
     "Galat Umum",
     "أخطاء شائعة",
     "Symptoms, cause, solution and verification for the errors you will actually see."),
    ("troubleshooting/collection", "troubleshooting", "troubleshooting", 20, "jobs",
     ["/api/v1/jobs", "/api/v1/dlq"],
     [],
     ["collection", "queued", "stuck", "failed", "koleksi"],
     "Collection Issues",
     "Masalah Koleksi",
     "مشاكل الجمع",
     "Investigations stuck in queued, failed jobs and empty results."),
    ("troubleshooting/database", "troubleshooting", "troubleshooting", 30, "health",
     [],
     [],
     ["database", "mysql", "sqlite", "persistence", "basis data"],
     "Database Issues",
     "Masalah Basis Data",
     "مشاكل قاعدة البيانات",
     "SQLite fallback surprises, access denied and data that disappears on restart."),
    ("troubleshooting/redis", "troubleshooting", "troubleshooting", 40, "health",
     [],
     [],
     ["redis", "queue", "rate limit"],
     "Redis Issues",
     "Masalah Redis",
     "مشاكل Redis",
     "Queue stalls and rate-limit behavior with and without Redis."),
    ("troubleshooting/browser", "troubleshooting", "troubleshooting", 50, "collectors",
     ["/api/v1/browser/health"],
     [],
     ["browser", "playwright", "peramban"],
     "Browser Issues",
     "Masalah Browser",
     "مشاكل المتصفح",
     "Headless pool failures, timeouts and blocked media."),
    ("troubleshooting/ai", "troubleshooting", "troubleshooting", 60, "ai-providers",
     ["/api/v1/ai/health"],
     [],
     ["ai", "provider", "latency", "models"],
     "AI Issues",
     "Masalah AI",
     "مشاكل الذكاء الاصطناعي",
     "Provider down, model discovery empty and slow answers."),
    ("troubleshooting/stix", "troubleshooting", "troubleshooting", 70, "stix",
     ["/api/v1/stix/validate", "/api/v1/misp/import"],
     [],
     ["stix", "misp", "validation", "import"],
     "STIX / MISP Issues",
     "Masalah STIX / MISP",
     "مشاكل STIX / MISP",
     "Validation failures and import mismatches."),
    # ---------------- reference ----------------
    ("reference/glossary", "reference", "glossary", 10, "search",
     [],
     [],
     ["glossary", "terms", "entity", "finding", "evidence", "glosarium", "istilah"],
     "Glossary",
     "Glosarium",
     "المسرد",
     "Every term that matters: entity to collection strategy, with examples."),
    ("reference/statuses", "reference", "reference", 20, "investigations",
     ["/api/v1/investigations"],
     [],
     ["status", "queued", "running", "completed", "failed", "cancelled"],
     "Statuses",
     "Status",
     "الحالات",
     "All async and lifecycle statuses and what each one promises."),
    ("reference/risk-scoring", "reference", "reference", 30, "risk",
     ["/api/v1/risk/target"],
     [],
     ["risk", "scoring", "0-100", "severity", "confidence", "skor"],
     "Risk Scoring",
     "Skoring Risiko",
     "تقييم المخاطر",
     "How 0-100 scores, factors, evidence and confidence combine."),
    ("reference/entity-types", "reference", "reference", 40, "entities",
     ["/api/v1/entities"],
     [],
     ["entity types", "company", "domain", "ip", "email", "jenis entitas"],
     "Entity Types",
     "Jenis Entitas",
     "أنواع الكيانات",
     "Every entity kind, its identity rules and its color."),
    ("reference/collection-strategies", "reference", "reference", 50, "collectors",
     ["/api/v1/strategy/decide"],
     [],
     ["strategy", "direct", "browser", "proxy", "bright data", "strategi"],
     "Collection Strategies",
     "Strategi Koleksi",
     "استراتيجيات الجمع",
     "The DIRECT to BRIGHT_DATA ladder and how the decider chooses."),
    ("reference/environment-variables", "reference", "reference", 60, "settings",
     [],
     [],
     ["env", "environment", "config", "variables", "lingkungan"],
     "Environment Variables",
     "Variabel Lingkungan",
     "متغيرات البيئة",
     "Every variable the platform reads, with defaults and production values."),
    # ---------------- top-level hubs ----------------
    ("ai-providers", "ai", "concept", 5, "ai-providers",
     ["/api/v1/ai/providers", "/api/v1/ai/providers/db", "/api/v1/ai/default"],
     ["23-ai-provider.png"],
     ["ai providers", "keys", "testing", "models", "ollama", "opencode", "defaults"],
     "AI Providers Guide",
     "Panduan Penyedia AI",
     "دليل مزودي الذكاء الاصطناعي",
     "Configure providers, guard keys, test live, discover models and set defaults."),
    ("settings", "administration", "concept", 45, "settings",
     ["/api/v1/settings/defaults", "/api/v1/settings/system", "/api/v1/flags"],
     ["26-settings.png"],
     ["settings", "defaults", "preferences", "pengaturan"],
     "Settings Guide",
     "Panduan Pengaturan",
     "دليل الإعدادات",
     "The sectioned settings shell: what is stored where, and what each save does."),
    ("troubleshooting", "troubleshooting", "concept", 5, "health",
     [],
     [],
     ["troubleshooting", "help", "errors", "bantuan"],
     "Troubleshooting Index",
     "Indeks Pemecahan Masalah",
     "فهرس استكشاف الأخطاء",
     "Start here when something behaves unexpectedly; every guide follows symptoms, cause, solution, verification."),
    ("functional-status", "reference", "reference", 5, "health",
     ["/healthz", "/readyz", "/api/version"],
     ["27-system-health.png"],
     ["status", "fonctional", "what works", "requirements"],
     "Functional Status",
     "Status Fungsional",
     "الحالة الوظيفية",
     "What works out of the box, what needs configuration, and what needs external tools."),
    # ---------------- changelog ----------------
    ("changelog", "changelog", "reference", 10, "dashboard",
     ["/api/version"],
     [],
     ["changelog", "version", "releases", "rilis"],
     "Changelog",
     "Catatan Rilis",
     "سجل التغييرات",
     "Versions from the application itself — never fabricated."),
]

# Frontend hash route -> docs path (contextual help + help drawer + empty states).
VIEW_DOCS = {
    "dashboard": "getting-started/dashboard",
    "login": "getting-started/login",
    "new-investigation": "investigations/create-investigation",
    "investigations": "investigations/investigation-lifecycle",
    "investigation": "investigations/investigation-lifecycle",
    "cases": "evidence/cases",
    "case": "evidence/cases",
    "search": "search",
    "entities": "intelligence/entities",
    "entity": "intelligence/entity-resolution",
    "graph": "intelligence/graph",
    "timeline": "intelligence/timeline",
    "targets": "discovery/targets",
    "target": "discovery/targets",
    "attack": "discovery/attack-surface",
    "recon": "discovery/reconnaissance",
    "jobs": "investigations/collection",
    "job": "investigations/collection",
    "collectors": "discovery/collectors",
    "connectors": "discovery/connectors",
    "data-sources": "discovery/data-sources",
    "projects": "discovery/data-sources",
    "project": "discovery/data-sources",
    "findings": "intelligence/findings",
    "finding": "intelligence/findings",
    "indicators": "intelligence/indicators",
    "risk": "intelligence/risk",
    "threat": "intelligence/threat-intelligence",
    "feed": "intelligence/feed",
    "intel-feed": "intelligence/feed",
    "watchlists": "monitoring/watchlists",
    "alerts": "monitoring/alerts",
    "alert": "monitoring/alerts",
    "workflows": "monitoring/workflows",
    "workflow": "monitoring/workflows",
    "evidence": "evidence/evidence",
    "documents": "evidence/documents",
    "reports": "evidence/reports",
    "stix": "integrations/stix",
    "external-apis": "integrations/external-apis",
    "apikeys": "administration/api-keys",
    "security-tools": "integrations/security-tools",
    "settings": "administration/settings",
    "ai-providers": "ai/providers",
    "ai": "ai/providers",
    "users": "administration/users",
    "audit": "administration/audit-log",
    "health": "administration/system-health",
    "operations": "investigations/collection",
    "schedules": "investigations/collection",
    "datasets": "evidence/documents",
    "dataset": "evidence/documents",
    "research": "ai/research",
    "runs": "ai/research",
    "analytics": "intelligence/findings",
    "opps": "intelligence/findings",
    "transforms": "intelligence/pivoting",
    "events": "intelligence/timeline",
    "prices": "discovery/targets",
    "articles": "discovery/connectors",
    "reviews": "discovery/connectors",
    "changes": "discovery/reconnaissance",
    "claims": "evidence/claims",
    "costs": "ai/privacy",
    "orgs": "administration/organizations",
    "reliability": "discovery/targets",
    "webhooks": "monitoring/webhooks",
    "webhook": "monitoring/webhooks",
}

# Investigation lifecycle stages for the visual workflow page.
LIFECYCLE = [
    ("Search", "investigations/target-types", "Find the starting point: a domain, IP, email or keyword."),
    ("Target", "investigations/target-types", "Validate the target and pick its type."),
    ("Scope", "investigations/scope", "Choose what to collect: DNS, TLS, tech, content and more."),
    ("Collect", "investigations/collection", "Queued to completed — every state is visible."),
    ("Normalize", "discovery/collectors", "Raw captures become clean, comparable records."),
    ("Entity Resolution", "intelligence/entity-resolution", "Mentions become confident identities."),
    ("Graph", "intelligence/graph", "Relationships you can traverse and pivot."),
    ("Correlate", "intelligence/pivoting", "Shared infrastructure becomes findings."),
    ("Risk", "intelligence/risk", "Explainable 0-100 scores with evidence."),
    ("Findings", "intelligence/findings", "Triage what correlation surfaced."),
    ("Evidence", "evidence/evidence", "Preserve sources with provenance."),
    ("Case", "evidence/cases", "Bundle notes, tasks, members and links."),
    ("Report", "evidence/reports", "Export web, PDF, CSV, JSON, XLSX or Markdown."),
    ("Monitor", "monitoring/watchlists", "Watchlists, alerts and workflows keep watching."),
]

GLOSSARY = [
    ("Entity", "Entitas", "كيان",
     "A distinct real-world thing the platform tracks: person, company, domain, IP, email, technology.",
     "Resolution turns noisy mentions into one confident identity; everything else hangs off entities.",
     "Acme Corporation resolved from three different spellings across two sources."),
    ("Indicator", "Indikator", "مؤشر",
     "A distilled signal of interest, often an IOC: a malicious IP, a phishing domain, a bad hash.",
     "Indicators feed STIX/MISP exchange and watchlist matching.",
     "203.0.113.10 flagged after resolving three phishing domains in one hour."),
    ("Finding", "Temuan", "نتيجة",
     "A correlated, analyst-triaged result with severity, confidence, evidence and lineage.",
     "Findings are the unit of triage: OPEN to CONFIRMED, ACCEPTED or FALSE_POSITIVE, ending at RESOLVED — never silently dropped.",
     "Exposed admin panel on acme.example, severity high, confidence 0.8."),
    ("Evidence", "Bukti", "دليل",
     "A preserved source record: URL, timestamp, hash and snippet proving what was seen.",
     "No claim or finding ships without evidence_ids pointing here.",
     "HTTP capture of https://acme.example with content hash at collection time."),
    ("Claim", "Klaim", "ادعاء",
     "An assertion that must be verified against evidence before anyone trusts it.",
     "Verification marks claims confirmed or contradicted; contradictions raise flags.",
     "Claim: acme.example runs nginx — verified against two captures."),
    ("Investigation", "Investigasi", "تحقيق",
     "A scoped work unit with target, depth, scope, lifecycle status and linked entities.",
     "Investigations move open to investigating to completed; cases bundle them for action.",
     "Acme exposure review: domain target, standard profile, completed."),
    ("Case", "Kasus", "قضية",
     "The action container: notes, tasks, members, links to entities, findings and evidence.",
     "Cases turn analysis into assigned, trackable work ending in a report.",
     "Acme case: two findings, one evidence record, three tasks."),
    ("Target", "Target", "هدف",
     "A monitored site or identifier inside a project, with a learning profile.",
     "Targets carry reliability scores from real collection history.",
     "https://acme.example watched for TLS and technology changes."),
    ("Collector", "Kolektor", "جامع",
     "An engine that fetches data: the Go collector, the browser pool, or an API adapter.",
     "Collectors escalate along the strategy ladder when the simple path fails.",
     "Go collector fetched acme.example directly in 1.2s."),
    ("Connector", "Konektor", "موصل",
     "A configured RSS, paginated REST or CSV source that can be tested and executed.",
     "Connectors turn outside feeds into articles and datasets on a schedule.",
     "Sector-news RSS executed nightly into the articles store."),
    ("Intelligence Graph", "Graf Intelijen", "الرسم البياني الاستخباري",
     "Nodes and edges with confidence: companies own domains, domains resolve to IPs.",
     "Traversal and shortest path reveal relationships no single record shows.",
     "Acme OWNS acme.example RESOLVES_TO 203.0.113.10."),
    ("Pivot", "Pivot", "انتقال",
     "A transform that expands one entity into related ones: domain to IP to domain.",
     "Pivoting is how one clue becomes a network.",
     "From acme.example to its IP to three sibling domains on the same host."),
    ("Risk", "Risiko", "مخاطر",
     "An explainable 0-100 score built from factors, each backed by evidence.",
     "Risk is an analytical signal for prioritization — not proof of malicious activity.",
     "acme.example scores 72: exposed panel (+30), outdated library (+25), new cert (+17)."),
    ("Watchlist", "Daftar Pantau", "قائمة المراقبة",
     "A keyword, company or domain subscription evaluated against new intelligence.",
     "Matches raise alerts; evaluation can run on demand or on schedule.",
     "Watch acme so every new mention raises an alert."),
    ("Alert", "Peringatan", "تنبيه",
     "A fired notification with severity, status and acknowledge/resolve lifecycle.",
     "Alerts queue human attention; bulk operations keep the queue manageable.",
     "New asset alert for api.acme.example, severity info."),
    ("Workflow", "Alur Kerja", "سير العمل",
     "Trigger-to-action automation with visible runs, idempotent retry and cancel.",
     "Workflows connect detection to response without hiding state.",
     "On high finding: open a case and notify the webhook."),
    ("STIX", "STIX", "STIX",
     "Structured Threat Information Expression 2.1: bundles of typed threat objects.",
     "The platform exports a documented subset, validates it, and imports with dedupe.",
     "Acme indicators exported as a STIX 2.1 bundle for sharing."),
    ("MISP", "MISP", "MISP",
     "Malware Information Sharing Platform events with attributes and galaxies.",
     "Export events with attributes and tags; import maps them back to entities.",
     "Acme event with three attributes pushed to the sharing community."),
    ("IOC", "IOC", "مؤشر اختراق",
     "Indicator of Compromise: an artifact observed in malicious activity.",
     "IOCs are indicators with teeth — handle them as response triggers.",
     "Phishing URL first seen in the feed, now on the domain watchlist."),
    ("OSINT", "OSINT", "استخبارات مفتوحة",
     "Open-source intelligence: insight from publicly available data.",
     "The platform only collects public data and respects robots.txt and terms.",
     "Certificate transparency logs revealing a new subdomain."),
    ("Attack Surface", "Permukaan Serangan", "سطح الهجوم",
     "The sum of exposed assets: subdomains, IPs, ports, technologies, certificates.",
     "You cannot defend what you cannot see; the overview lists it all.",
     "Fourteen hosts, two outdated libraries, one expiring certificate."),
    ("Reconnaissance", "Reconnaissance", "استطلاع",
     "Active information gathering: DNS, TLS, technology and WHOIS/RDAP scans.",
     "Each scan is recorded with its method so results stay reproducible.",
     "Deep scan of acme.example captured DNS, TLS and RDAP in one pass."),
    ("Data Source", "Sumber Data", "مصدر البيانات",
     "Any origin of records: projects, targets, connectors or documents.",
     "Source health and reliability decide how much to trust what arrives.",
     "The sector RSS connector, healthy for 30 consecutive runs."),
    ("Research Run", "Jalannya Riset", "جولة بحث",
     "A planned, analyzed and finished AI-assisted research session with exports.",
     "Runs keep AI work reproducible instead of chat-shaped and forgettable.",
     "Competitor pricing research finished with a Markdown export."),
    ("Entity Resolution", "Resolusi Entitas", "حل الكيانات",
     "Matching, merging and splitting mentions into canonical entities.",
     "Confidence scores record how sure the match is — and what would change it.",
     "Three admin@ variants merged into one email entity at 0.92."),
    ("Data Lineage", "Silsilah Data", "نسب البيانات",
     "The chain from raw collection to finding: every hop recorded.",
     "Lineage makes findings auditable and retractions possible.",
     "Finding 7 traces to job 3, document 5 and evidence 9."),
    ("Confidence", "Kepercayaan", "الثقة",
     "A 0-1 or percentage estimate of how sure a record, match or score is.",
     "Confidence separates strong leads from noise without hiding either.",
     "Entity match at 0.92 confidence after three corroborating sources."),
    ("Severity", "Keparahan", "الخطورة",
     "Critical, high, medium, low or info: how urgently a finding or alert needs humans.",
     "Severity drives triage order and workflow triggers.",
     "Exposed admin panel: high severity, open status."),
    ("Collection Strategy", "Strategi Koleksi", "استراتيجية الجمع",
     "The escalation ladder DIRECT, API, BROWSER, OWN_PROXY, BRIGHT_DATA.",
     "The decider picks the cheapest strategy that can succeed for each target.",
     "acme.example collected DIRECT; the JS-heavy portal needed BROWSER."),
]

# Deterministic screenshot plan. `view` is the frontend hash route photographed.
SHOTS = [
    {"file": "01-login.png", "view": "login", "title": "Sign in",
     "desc": "Web Intelligence sign-in view with token and API-key authentication.",
     "kind": "desktop"},
    {"file": "02-dashboard.png", "view": "dashboard", "title": "Dashboard",
     "desc": "Web Intelligence hero dashboard with KPIs, trends, risk and activity.",
     "kind": "desktop"},
    {"file": "03-new-investigation.png", "view": "new-investigation", "title": "New Investigation wizard",
     "desc": "Web Intelligence New Investigation wizard showing target type selection.",
     "kind": "desktop"},
    {"file": "04-target-type.png", "view": "new-investigation", "title": "Target type",
     "desc": "Target type selection inside the New Investigation wizard.",
     "kind": "desktop"},
    {"file": "05-target.png", "view": "new-investigation", "title": "Enter target",
     "desc": "Entering a domain target in the New Investigation wizard.",
     "kind": "desktop"},
    {"file": "06-scope.png", "view": "new-investigation", "title": "Scope selection",
     "desc": "Scope selection: DNS, subdomains, TLS, technologies and more.",
     "kind": "desktop"},
    {"file": "07-sources.png", "view": "data-sources", "title": "Data sources",
     "desc": "Projects, targets and connectors as data sources.",
     "kind": "desktop"},
    {"file": "08-review.png", "view": "new-investigation", "title": "Review and start",
     "desc": "Reviewing the investigation before starting collection.",
     "kind": "desktop"},
    {"file": "09-queued.png", "view": "job", "title": "Collection job queued",
     "desc": "A newly created collection job on its scan page showing the queued state.",
     "kind": "desktop"},
    {"file": "10-running.png", "view": "job", "title": "Collection job running",
     "desc": "The same collection job running, with attempts accumulating on the scan page.",
     "kind": "desktop"},
    {"file": "11-completed.png", "view": "job", "title": "Collection job succeeded",
     "desc": "The collection job finished with success, attempts, prices and changes attached.",
     "kind": "desktop"},
    {"file": "12-findings.png", "view": "findings", "title": "Findings",
     "desc": "Triaging correlated findings with severity and confidence.",
     "kind": "desktop"},
    {"file": "13-entities.png", "view": "entities", "title": "Entities",
     "desc": "Entity list with kinds and confidence scores.",
     "kind": "desktop"},
    {"file": "14-graph.png", "view": "graph", "title": "Intelligence graph",
     "desc": "The intelligence graph: companies, domains and infrastructure linked.",
     "kind": "desktop"},
    {"file": "15-risk.png", "view": "risk", "title": "Risk analysis",
     "desc": "Explainable 0-100 risk with factors and evidence.",
     "kind": "desktop"},
    {"file": "16-timeline.png", "view": "timeline", "title": "Timeline",
     "desc": "Chronological event timeline of the investigation.",
     "kind": "desktop"},
    {"file": "17-evidence.png", "view": "evidence", "title": "Evidence",
     "desc": "Evidence records with source, timestamp and integrity.",
     "kind": "desktop"},
    {"file": "18-case.png", "view": "cases", "title": "Case",
     "desc": "Case workspace with notes, tasks and linked objects.",
     "kind": "desktop"},
    {"file": "19-report.png", "view": "reports", "title": "Report",
     "desc": "Generated report with export formats.",
     "kind": "desktop"},
    {"file": "20-watchlist.png", "view": "watchlists", "title": "Watchlist",
     "desc": "Watchlist entries evaluated against new intelligence.",
     "kind": "desktop"},
    {"file": "21-alert.png", "view": "alerts", "title": "Alerts",
     "desc": "Alert queue with acknowledge and resolve actions.",
     "kind": "desktop"},
    {"file": "22-workflow.png", "view": "workflows", "title": "Workflow",
     "desc": "Workflow automation with runs and retry.",
     "kind": "desktop"},
    {"file": "23-ai-provider.png", "view": "ai-providers", "title": "AI providers",
     "desc": "AI provider configuration with live connection testing.",
     "kind": "desktop"},
    {"file": "24-stix.png", "view": "stix", "title": "STIX",
     "desc": "STIX 2.1 export, validation and import.",
     "kind": "desktop"},
    {"file": "25-misp.png", "view": "stix", "title": "MISP",
     "desc": "MISP event exchange mapped to entities.",
     "kind": "desktop"},
    {"file": "26-settings.png", "view": "settings", "title": "Settings",
     "desc": "Administration settings: security, collectors, scheduler and storage.",
     "kind": "desktop"},
    {"file": "27-system-health.png", "view": "health", "title": "System health",
     "desc": "System health with readiness and the system doctor.",
     "kind": "desktop"},
    {"file": "28-api.png", "view": "external-apis", "title": "External APIs",
     "desc": "API keys and external integration endpoints.",
     "kind": "desktop"},
    {"file": "29-docs-home.png", "view": "__docs__", "title": "Documentation home",
     "desc": "The documentation portal home with task-based paths.",
     "kind": "desktop"},
    {"file": "30-first-investigation.png", "view": "__docs__/getting-started/first-investigation",
     "title": "First investigation tutorial",
     "desc": "The step-by-step first-investigation tutorial with screenshots.",
     "kind": "desktop"},
    {"file": "31-search.png", "view": "search", "title": "Global search console",
     "desc": "The Global Search console with mode and filter controls.",
     "kind": "desktop"},
    {"file": "32-search-results.png", "view": "search", "title": "Search results",
     "desc": "Ranked search results with per-result actions.",
     "kind": "desktop"},
    {"file": "33-security-tools.png", "view": "security-tools", "title": "Security tools",
     "desc": "Collection and verification tooling with honest availability states.",
     "kind": "desktop"},
    {"file": "34-external-apis.png", "view": "external-apis", "title": "External APIs",
     "desc": "Outside-client integration with key management.",
     "kind": "desktop"},
    {"file": "m-dashboard.png", "view": "dashboard", "title": "Dashboard on mobile",
     "desc": "The dashboard on a 390px mobile viewport.",
     "kind": "mobile"},
    {"file": "m-docs-home.png", "view": "__docs__", "title": "Docs on mobile",
     "desc": "The documentation portal on a 390px mobile viewport.",
     "kind": "mobile"},
]


# Extra API prefixes merged with each page's own list (keeps PAGES readable).
# keys are doc slugs; values extend coverage so API_COVERAGE can reach 100%.
API_EXTRA = {
    "index": ["/api/version", "/healthz", "/readyz", "/metrics", "/api/v1/i18n"],
    "getting-started/overview": ["/api/version", "/api/v1/dashboard", "/api/v1/i18n"],
    "getting-started/dashboard": ["/api/v1/dashboard", "/api/v1/feed"],
    "investigations/create-investigation": ["/api/v1/schedules"],
    "investigations/profiles": ["/api/v1/investigations"],
    "investigations/collection": ["/api/v1/schedules", "/api/v1/operations",
                                  "/api/v1/worker/tick"],
    "discovery/reconnaissance": ["/api/v1/changes", "/api/v1/strategy/decide"],
    "discovery/collectors": ["/api/v1/collectors", "/api/v1/strategy/decide"],
    "intelligence/graph": ["/api/v1/graph"],
    "api/graph": ["/api/v1/graph"],
    "intelligence/pivoting": ["/api/v1/transforms"],
    "intelligence/timeline": ["/api/v1/events"],
    "intelligence/threat-intelligence": [
        "/api/v1/intel/competitors/compare", "/api/v1/intel/news/summarize",
        "/api/v1/intel/reviews", "/api/v1/articles", "/api/v1/reviews",
        "/api/v1/opportunities", "/api/v1/analytics", "/api/v1/prices",
        "/api/v1/quality/score", "/api/v1/correlate/prices"],
    "intelligence/feed": ["/api/v1/feed"],
    "evidence/documents": ["/api/v1/datasets", "/api/v1/documents"],
    "ai/research": ["/api/v1/research"],
    "ai/providers": ["/api/v1/ai/provider-presets", "/api/v1/ai/credentials/inventory"],
    "api/ai": ["/api/v1/ai/provider-presets", "/api/v1/ml", "/api/v1/ai/default",
               "/api/v1/ai/credentials/inventory"],
    "monitoring/workflows": ["/api/v1/maintenance"],
    "administration/users": ["/api/v1/users", "/api/v1/memberships"],
    "administration/settings": [
        "/api/v1/settings",
        "/api/v1/admin/data-quality", "/api/v1/admin/retention/run",
        "/api/v1/admin/demo", "/api/v1/admin/first-run", "/api/v1/admin/backup",
        "/api/v1/flags", "/api/v1/verticals", "/api/v1/billing", "/api/v1/costs"],
    "administration/system-health": ["/api/v1/operations", "/healthz", "/readyz",
                                     "/metrics", "/api/version"],
    "administration/backup": ["/api/v1/admin/backup"],
    "security/authentication": ["/api/v1/auth"],
    "api/authentication": ["/api/v1/auth"],
    "api/overview": ["/api/version", "/api/v1/docs"],
}


def api_prefixes(page) -> list:
    base = list(page[5] or [])
    for extra in API_EXTRA.get(page[0], []):
        if extra not in base:
            base.append(extra)
    return base


def page_by_slug(slug: str):
    for p in PAGES:
        if p[0] == slug:
            return p
    return None


def section_by_id(sid: str):
    for s in SECTIONS:
        if s["code"] == sid:
            return s
    return None


def section_name(sid: str, lang: str) -> str:
    s = section_by_id(sid)
    if not s:
        return sid
    return s["name"].get(lang) or s["name"]["en"]


def pages_in_section(sid: str):
    return sorted([p for p in PAGES if p[1] == sid], key=lambda p: p[3])


def title_of(page, lang: str) -> str:
    idx = {"en": 8, "id": 9, "ar": 10}[lang] if lang in ("en", "id", "ar") else 8
    return page[idx] or page[8]


def desc_of(page, lang: str) -> str:
    if lang == "id":
        return page[12] if len(page) > 12 and page[12] else page[11]
    if lang == "ar":
        return page[12] if len(page) > 12 and page[12] else page[11]
    return page[11]
